name: Git Sweep Merged and Stale
author: Rodney Hawkins (rod.codes)
description: Deletes old branches older than X days and merged branches. Based on `git-sweep`.
inputs:
  delete_stale_after_days:
    description: 'After how many days should a branch be stale `X`?'
    required: true
    default: '365'
  action:
    description: 'Type of action? ("preview" (dry-run) or "cleanup")'
    required: true
    default: 'preview'
  skip:
    description: 'Comma seperated string list of branches to ignore'
    required: false
    default: "main,develop,master"
  which_master_main:
    description: 'The name of what you consider the main or master branch'
    required: false
    default: "master"
runs:
  using: composite
  steps:
    - id: which-version
      run: python -c "import sys; print(sys.version)"
      shell: bash
    - id: ensure-python36-and-above
      run: ${{ github.action_path }}/bin/ensure_python
      shell: bash
    - id: install-run-git-sweep-merged-and-stale
      run:
        sudo apt-get install git && cd ${{ github.action_path }} && pip install . --user && cd ${{ github.workspace }} && PATH="$PATH:/home/runner/.local/bin" git-sweep-merged-and-stale ${{ inputs.action }} --force --master ${{ inputs.which_master_main }} --skip ${{ inputs.skip }} --delete_stale_after_days ${{ inputs.delete_stale_after_days }}
      shell: bash
branding:
  icon: 'archive'
  color: 'white'