name: Build on any tag update or push
on:
  create:
    tags:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build_or_upload_if_tag_to_pypi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']
    steps:
    - name: git
      run: sudo apt-get install git
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user .
        pip install twine wheel
    - uses: casperdcl/deploy-pypi@v2
      with:
        build: true
        pip: true
        password: ${{ secrets.SECRET_PYPI_RODCODES_API_TOKEN }}
        upload: ${{ github.event_name == 'create' && github.event.ref_type ==  'tag' }}
