name: Automatically update the latest-tag
on:

  push:
    branches: [ master ]

  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
