name: Push tag to PyPi
on: 
  workflow_run:
    workflows: ["Pytest and tag latest and beta"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to Push'
        default: 'refs/tags/1.0b1'
        required: true

jobs:
  force_upload_tag:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']
    steps:
    - name: Git install
      run: sudo apt-get install git
    - name: Print Context
      env:
        INPUT: ${{ github.event.inputs.tag }}
        TAG: ${{ format('{0}{1}', github.event.inputs.tag, 'refs/tags/1.0b1') }}
      run: echo $TAG & echo $INPUT
    - uses: actions/checkout@v2
      with:
        ref: ${{ format('{0}{1}', github.event.inputs.tag, 'refs/tags/1.0b1') }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user .
        pip install twine wheel
    - uses: casperdcl/deploy-pypi@v2
      with:
        build: true
        pip: true
        password: ${{ secrets.SECRET_PYPI_RODCODES_API_TOKEN }}