name: Pytest and tag latest and beta
on:
  pull_request:
    branches: 
      - '*'
  push:
    branches:
      - 'master'

jobs:
  pytest_coverage_tool:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [ '3.6', '3.7', '3.8', '3.9']
    steps:
    - name: git
      run: sudo apt-get install git
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
  run_data:
    needs: [pytest_coverage_tool]
    runs-on: ubuntu-latest
    steps:
      - name: Tell me about what's going on
        env:
          ACTOR: ${{ github.actor }}
          REF: ${{ github.ref }}
        run: echo $ACTOR && echo $REF
  build_latest_tag:
    if: github.ref == 'refs/heads/master' && github.actor == 'rodvdka'
    needs: [run_data]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
  build_latest_tag_beta:
    if: github.ref == 'refs/heads/master' && github.actor == 'rodvdka'
    needs: [run_data]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          tag-name: 1.0b1
  test_stale:
    needs: [build_latest_tag]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rodvdka/git-sweep-merged-and-stale@latest
      - uses: rodvdka/git-sweep-merged-and-stale@latest
        with:
          action: "cleanup"
