name: Automatically update the test-tag
on:

  push:
    branches:
      - "test*"

  workflow_dispatch:


jobs:
  build_latest_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          tag-name: test

  test_stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rodvdka/git-sweep-merged-and-stale@test
      - uses: rodvdka/git-sweep-merged-and-stale@test
        with:
          action: "cleanup"
